### ISSUE TITLE
Todo Sprint 2

### ISSUE THREAD

**Issue by ItsRD** [ItsRD/tc-export#10]
# Client side
### Componenten
- [x] Bij aanmaken -> unit op alfabetische volgorde.
- [x] Delete knopje wanneer er dmv jquery een nieuwe component kan worden toegevoegd
- [x] Bij de knop "Add Another Component" leegmaken van de nieuwe component velden
- [x] TypeAhead unit bij het toevoegen van componenten
- [x] Mogelijkheid tot kopiëren van oude componenten
- [x] Controleren van componenten bij het toevoegen van nieuwe

### Orders
- [x] Bij akkoord geven van order -> amount wilt soms niet werken
- [x] Verwijderen van componenten uit order bij akkoord geven op order.
- [x] Overzicht bij orders -> Kolom erbij 'total price'
- [x] "Yet in treatment" veranderen naar "In Progress"
- [x] "Sent to client" veranderen naar sent (alleen client side)
- [x] Overzicht orders -> trackingnummer erbij zetten
- [x] Overzicht orders -> created date in eerste kolom zetten
- [x] Datatable toevoegen aan orders en unit table

### Rechten
- [x] Management kan aanvragers aan en uit zetten

### Unit
- [x] Opmerking (comment) toevoegen 

# Admin side
### Orders
- [x] Number, amount en naam kunnen aanpassen van componenten.
- [x] Controleren van gegevens bij het aanmaken van order
- [x] Select2 integreren 
- [x] Sorteren op datum
- [x] Wanneer trackingcode wordt ingevuld -> mail icoon laten zien (nu laat hij alleen zien bij Refresh)
- [x] Exporteren van order
- [x] Margin bereken gaat soms niet goed, weet niet waarom en wanneer precies 

### Componenten
- [x] Gebruiker laten zien in table van overzicht componenten
- [x] Particpant kan alle orders zijn van andere bedrijven

### Company
- [x] Toevoegen van fields: KVK, NAW, BTW-nummer
- [x] De tabjes veranderen in aparte pagina's
- [x] Knop met show users toevoegen -> onclick: alle gebruikers inladen dmv ajax

# Overig
### Mail
- [x] Bij akkoord van order, mail versturen naar aanvrager en financiële man van het bedrijf

### Navigatiebalk
- [x] Volgorde veranderen (Components & Orders, Company (met erin users), Fuel type, Vehicle type)

### Roles
- [x] Roles doet het niet helemaal goed

### Portaal
- [x] Beveiligen portaal dmv .htaccess

### DataTables
- [x] Default veranderen van 10 naar 50
