### ISSUE TITLE
Algemene TODO

### ISSUE THREAD

**Issue by remcovisser** [ItsRD/tc-export#8]
- [x] Index pagina voor een user (Nieuwe offerteaanvraag, Reeds aangevraagde offerte)
- [ ] Excel achtig bestand waar een onderverdeling is per unit met alle reeds aangevraagde onderdelen
- [x] Bestelproces stap 1
- [x] Bestelproces stap 2
- [x] Bestelproces stap 3
- [x] Bestelproces stap 4
- [x] Bestelproces stap 5
- [x] Bestelproces stap 6 
- [ ] Vanuit reeds bestelde producten moet er een optie zijn om een product toe te voegen aan je componenten.
